GET http://localhost:3003/api/blogs/
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt1cnRnYW4iLCJpZCI6IjYxZGVkYjc1MTRjZjhhYWQxYzdlZWY0ZiIsImlhdCI6MTY0MjA4MzQ4MSwiZXhwIjoxNjQyMDg3MDgxfQ.bmrfBC9ZvBbA0JKND2v6a7im-yqR9iEHYlSJhRX4i_E

{
    "title" : "FAT Dog",
    "author" : "ISJHD Gan",
    "url" : "haha",
    "likes" : 1000230,
    "userId" : "61dedb7514cf8aad1c7eef4f"
}

###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username" : "LOL",
    "name" : "Hames Gan",
    "password" : "cool",
    "blogs" : []
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "kurtgan",
    "password": "haha"
}